[default]
auto_detect_solc = true
libs = ['lib']
optimizer = true
optimizer_runs = 200
out = 'out'
src = 'src'
test = 'test'
gas_reports = ['*']
remappings = [
  "forge-std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts/",
  "ds-test/=lib/ds-test/src/"
]
